### ISSUE TITLE
Phylanx iteration doesn't work

### ISSUE THREAD

**Issue by stevenrbrandt** [STEllAR-GROUP/phylanx#1098]
The code
```
@Phylanx(debug=True)
def foo():
    f = [1, 2, 3]
    for k in f:
        print(k)

foo()
```
Produces the output
```
define(
    foo,
    lambda(
        block(
            define(
                f,
                list(1, 2, 3)
            ),
            for_each(
                lambda(
                    k,
                    cout(k)
                ),
                f
            )
        )
    )
)
1
2
3
```
Which is fine, but running this code through the physl interpreter results in this:
```
0x7f0aee3022e2  : ??? + 0x7f0aee3022e2 in /usr/local/lib64/libhpxd.so.1
{locality-id}: 0
{hostname}: [ ]
{process-id}: 4543
{os-thread}: 37, worker-thread#37
{thread-id}: 000000004800e1c0
{thread-description}: /phylanx/access-argument$0$k/0$12$26::eval
{state}: state_running
{auxinfo}:
{file}: /home/jovyan/phylanx/src/execution_tree/primitives/access_argument.cpp
{line}: 80
{function}: virtual hpx::lcos::future<phylanx::execution_tree::primitive_argument_type> phylanx::execution_tree::primitives::access_argument::eval(const primitive_arguments_type&, phylanx::execution_tree::eval_context) const
{what}: Assertion 'operands_.size() > 1 && (valid(operands_[1]) || is_explicit_nil(operands_[1]))' failed: HPX(assertion_failure)
```

**Comment by khuck** [comment]
I am confused.  The original Phylanx code has a bug, are you saying if the original Phylanx code is changed and then re-executed it crashes, or just changing the generated PhySL makes it crash?  The original code *should* be:
@Phylanx(debug=True)
def foo():
    f = [1, 2, 3]
    for k in f:
        print(k)
Right?  Otherwise, it will just print the full array 3 times.

Thanks -
Kevin
--
Kevin Huck, PhD
Research Associate / Computer Scientist
OACISS - Oregon Advanced Computing Institute for Science and Society
University of Oregon
khuck@cs.uoregon.edu
http://tau.uoregon.edu

**Comment by stevenrbrandt** [comment]
@khuck your comment was valid before I edited the problem description. :)
