### ISSUE TITLE
Errors building Phylanx

### ISSUE THREAD

**Issue by khuck** [STEllAR-GROUP/phylanx#37]
I am getting these errors when building on x86_64 with python 3.3.4 and gcc 7.1:

```
running build
running build_py
creating build
creating build/lib.linux-x86_64-3.3
creating build/lib.linux-x86_64-3.3/phylanx
copying /home/users/khuck/src/phylanx/src/phylanx/python/phylanx/__init__.py -> build/lib.linux-x86_64-3.3/phylanx
creating build/lib.linux-x86_64-3.3/phylanx/ast
copying /home/users/khuck/src/phylanx/src/phylanx/python/phylanx/ast/__init__.py -> build/lib.linux-x86_64-3.3/phylanx/ast
creating build/lib.linux-x86_64-3.3/phylanx/util
copying /home/users/khuck/src/phylanx/src/phylanx/python/phylanx/util/__init__.py -> build/lib.linux-x86_64-3.3/phylanx/util
running build_ext
copying /home/users/khuck/src/phylanx/build-delphi-x86_64-Linux-gcc/phylanx-Debug/bin/_phylanxd.cpython-33m.so -> /storage/users/khuck/src/phylanx/build-delphi-x86_64-Linux-gcc/phylanx-Debug/python/build/lib.linux-x86_64-3.3/phylanx
error: /home/users/khuck/src/phylanx/build-delphi-x86_64-Linux-gcc/phylanx-Debug/bin/_phylanxd.cpython-33m.so: No such file or directory
make[2]: *** [python/build/timestamp] Error 1
make[1]: *** [python/CMakeFiles/python_setup.dir/all] Error 2
make: *** [all] Error 2
```

When I look in that directory, I see _phylanxd.so, but not _phylanxd.cpython-33m.so.  I have no idea where this is coming from in the CMake infrastructure...

**Comment by hkaiser** [comment]
I still have to find out where and how the pybind11 cmake scripts decide on the naming of the generated extension module. 

There are three different pieces of code relying/determining what name is used:

- pybind11_add_module
- python setup.py build/install
- our cmake scripts dealing with naming of the library

All of this is currently out of whack, apparently - and obviously needs to be resolved asap.

**Comment by hkaiser** [comment]
Just to clarify: pybind11_add_module and setup.py seem to agree on the naming scheme. The problematic part is our cmake scripting which I have not gotten to be correct yet.

@khuck: may I ask you to post the full cmake output and make log for reference?

**Comment by khuck** [comment]
<script src="https://gist.github.com/khuck/7dea58edfcba148c0e2c10f8cfa41bd2.js"></script>

**Comment by khuck** [comment]
Sorry, https://gist.github.com/khuck/7dea58edfcba148c0e2c10f8cfa41bd2

**Comment by hkaiser** [comment]
@khuck in your case pybind11_add_module seems to disagree with the python setup tools what name should be used for the extension module - strange. The assumption that those agree was one of the underlying assumptions to the current cmake scripting :/

**Comment by khuck** [comment]
Is that because "python" is /usr/bin/python and "python3" is the one that CMake detected?  I don't have a "python" executable in my python3.3.4 installation.

**Comment by hkaiser** [comment]
Was this resolved now?

**Comment by khuck** [comment]
Nope. See http://ktau.nic.uoregon.edu:8020/waterfall, the x86_64-gcc7 build - http://ktau.nic.uoregon.edu:8020/builders/x86_64-gcc7-release/builds/3/steps/Compile%20Phylanx/logs/stdio

**Comment by monil01** [comment]
I found that....
The compilation problem came from the unavailability of library file from python lib directory of Delphi machine. Cmake functions of Phylanx look for libpythonX.Xm.so library and based on this name it generates suffix for Phylanx library. In Delphi, for python 3.3.4 directory there is no .so file that is why the name generation process became messed up. I have tried with python 3.6.0 and it compiles.

with python 3.6.0 
------------------------
It has libpython3.6m.so this library which is picked up by cmake and _phylanx.cpython-36m-x86_64-linux-gnu.so is generated.  That is why it does not fail. 

copying /home/users/mmonil/src/phylanx/tools/buildbot/build-delphi-x86_64-Linux-gcc/phylanx-Release/bin/_phylanx.cpython-36m-x86_64-linux-gnu.so -> /storage/users/mmonil/src/phylanx/tools/buildbot/build-delphi-x86_64-Linux-gcc/phylanx-Release/python/build/lib.linux-x86_64-3.6/phylanx

with python 3.3.4
-----------------------
It has libpython3.3m.a library instead of a  libpython3.3m.so file. so the cmake cannot pick the suffix to add to the Phylanx library and the generated file is _phylanxd.so without cpython suffix attached to it and when cmake search for the _phylanxd.cpython-33m.so file it does not find and it fails.

copying /home/users/khuck/src/phylanx/build-delphi-x86_64-Linux-gcc/phylanx-Debug/bin/_phylanxd.cpython-33m.so -> /storage/users/khuck/src/phylanx/build-delphi-x86_64-Linux-gcc/phylanx-Debug/python/build/lib.linux-x86_64-3.3/phylanx
error: /home/users/khuck/src/phylanx/build-delphi-x86_64-Linux-gcc/phylanx-Debug/bin/_phylanxd.cpython-33m.so: No such file or directory

The reason is, in the module, python 3.3.4 and 3.4.4 were built with a static flag that is why instead of .so file it generated .a file in the lib.

**Comment by khuck** [comment]
@hkaiser Is this a case we want to deal with, or should we expect that the user has python shared objects?

**Comment by hkaiser** [comment]
@khuck: uhh - I didn't even know there was an option to build the python libraries statically.

@monil01: thanks for your thorough analysis. Is there a way to detect which type of python libraries are installed? Our cmake scripts try to generate the correct name for the python extension module based on some (obviously insufficient) knowledge. The script is here: https://github.com/STEllAR-GROUP/phylanx/blob/master/cmake/Phylanx_GetPythonExtensionLocation.cmake. If we had a way to detect the built-type we could adapt this script to do 'the right thing'...

**Comment by hkaiser** [comment]
@khuck, @monil01: Can this be closed now?

**Comment by khuck** [comment]
I don't see why not.  This is a corner case, configuration based.
