### ISSUE TITLE
Last PhySL line cannot be a comment

### ISSUE THREAD

**Issue by parsa** [STEllAR-GROUP/phylanx#413]
PhySL compiler does not accept comments as the last line of code
e.g.
```
0+0
# Comment
```
```
exception caught:
Error! Incomplete parse: line 2:
#
^
: HPX(bad_parameter)
```

**Comment by hkaiser** [comment]
@parsa Right, this is a bug. But it can be easily fixed by adding the postskip flag to the parser invocation here: https://github.com/STEllAR-GROUP/phylanx/blob/master/src/ast/generate_ast.cpp#L231. The problem goes away if this gets changed to:
```
if (!boost::spirit::qi::phrase_parse(first, last, *expr, skipper, 
        boost::spirit::qi::skip_flag::postskip, asts))
{
    ...
}
```
An equivalent change should be applied here: https://github.com/STEllAR-GROUP/phylanx/blob/master/src/ast/generate_transform_rules.cpp#L48.

**Comment by parsa** [comment]
The reason #417 appeared to have solved the problem is because the in its test case there is newline at the end of the code. Therefore
```
0 + 0
// trailing comments

```
works but
```
0 + 0
//trailing comment
```
does not
