### ISSUE TITLE
Create performance counters for primitives

### ISSUE THREAD

**Issue by parsa** [STEllAR-GROUP/phylanx#96]
This should be done in a way that all primitives almost automatically have performance counters associated with each of them. We should at least create two performance counters for each of the primitives:

    /phylanx{locality#N/<primitive-name>}/invocation-count
    /phylanx{locality#N/<primitive-name>}/execution-time

**Comment by hkaiser** [comment]
The names for the counters should follow the established practice. Here is a list of possible names for the counters we should create for each of the primitives:

    /phylanx{locality#N/total}/<primitive>/count/eval
    /phylanx{locality#N/total}/<primitive>/time/eval
    /phylanx{locality#N/total}/<primitive>/count/direct-eval
    /phylanx{locality#N/total}/<primitive>/time/direct-eval

where `<primitive>` represents the primitive type the counter will return data for. 

All returned values should be cumulative, i.e. the values should represent the accumulated counts/times since the counter was reset last. The returned times should have nanosecond resolution.

Also, while discussing this, we decided that the counters should return a `std::vector<std::int64_t>` of values (i.e. the counter types should be `hpx::performance_counter::raw_values_counter` - note that this type does not exist yet, see https://github.com/STEllAR-GROUP/hpx/issues/3102).

The values in the returned array should be ordered based on the sequence number that is encoded in the primitive names (as they are registered in AGAS), see https://github.com/STEllAR-GROUP/phylanx/pull/143 for a description of the structure of the generated primitive names.

Examples for the counter names used would be:

     /phylanx{locality#0/total}/define-function/count/eval
     /phylanx{locality#0/total}/add/time/direct-eval

**Comment by hkaiser** [comment]
@parsa please have a look at https://github.com/STEllAR-GROUP/hpx/pull/3103, those changes will most probably needed for your work. Please comment over there if that's what you need for your work on the performance counters.

**Comment by hkaiser** [comment]
This will also require for https://github.com/STEllAR-GROUP/hpx/pull/3118 to be merged in order to be able to (re-)initialize the counters with the current list of instantiated primitives.

**Comment by hkaiser** [comment]
This was fixed by merging #176
